import { MARKETPLACE } from '../../../common/constants';
import { MarketplaceApplication } from '../../../common/types';

const buildWebsite = (index: number): string => `publisher${((index - 1) % 3) + 1}.local`;

export const MOCK_MARKETPLACE_DATA: Record<string, MarketplaceApplication> = {
  'com.demo.app1': {
    bundleId: 'com.demo.app1',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 1',
    publisherName: 'Publisher 1',
    publisherDomain: buildWebsite(1),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app1',
  },
  'com.demo.app2': {
    bundleId: 'com.demo.app2',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 2',
    publisherName: 'Publisher 2',
    publisherDomain: buildWebsite(2),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app2',
  },
  'com.demo.app3': {
    bundleId: 'com.demo.app3',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 3',
    publisherName: 'Publisher 3',
    publisherDomain: buildWebsite(3),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app3',
  },
  'com.demo.app4': {
    bundleId: 'com.demo.app4',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 4',
    publisherName: 'Publisher 4',
    publisherDomain: buildWebsite(4),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app4',
  },
  'com.demo.app5': {
    bundleId: 'com.demo.app5',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 5',
    publisherName: 'Publisher 5',
    publisherDomain: buildWebsite(5),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app5',
  },
  'com.demo.app6': {
    bundleId: 'com.demo.app6',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 6',
    publisherName: 'Publisher 6',
    publisherDomain: buildWebsite(6),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app6',
  },
  'com.demo.app7': {
    bundleId: 'com.demo.app7',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 7',
    publisherName: 'Publisher 7',
    publisherDomain: buildWebsite(7),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app7',
  },
  'com.demo.app8': {
    bundleId: 'com.demo.app8',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 8',
    publisherName: 'Publisher 8',
    publisherDomain: buildWebsite(8),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app8',
  },
  'com.demo.app9': {
    bundleId: 'com.demo.app9',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 9',
    publisherName: 'Publisher 9',
    publisherDomain: buildWebsite(9),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app9',
  },
  'com.demo.app10': {
    bundleId: 'com.demo.app10',
    marketplace: MARKETPLACE.googlePlay,
    name: 'Demo App 10',
    publisherName: 'Publisher 10',
    publisherDomain: buildWebsite(10),
    marketplaceUrl: 'https://play.google.com/store/apps/details?id=com.demo.app10',
  },
  'com.demo.ios1': {
    bundleId: 'com.demo.ios1',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 1',
    publisherName: 'Publisher 11',
    publisherDomain: buildWebsite(11),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-1/id1000000001',
  },
  'com.demo.ios2': {
    bundleId: 'com.demo.ios2',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 2',
    publisherName: 'Publisher 12',
    publisherDomain: buildWebsite(12),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-2/id1000000002',
  },
  'com.demo.ios3': {
    bundleId: 'com.demo.ios3',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 3',
    publisherName: 'Publisher 13',
    publisherDomain: buildWebsite(13),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-3/id1000000003',
  },
  'com.demo.ios4': {
    bundleId: 'com.demo.ios4',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 4',
    publisherName: 'Publisher 14',
    publisherDomain: buildWebsite(14),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-4/id1000000004',
  },
  'com.demo.ios5': {
    bundleId: 'com.demo.ios5',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 5',
    publisherName: 'Publisher 15',
    publisherDomain: buildWebsite(15),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-5/id1000000005',
  },
  'com.demo.ios6': {
    bundleId: 'com.demo.ios6',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 6',
    publisherName: 'Publisher 16',
    publisherDomain: buildWebsite(16),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-6/id1000000006',
  },
  'com.demo.ios7': {
    bundleId: 'com.demo.ios7',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 7',
    publisherName: 'Publisher 17',
    publisherDomain: buildWebsite(17),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-7/id1000000007',
  },
  'com.demo.ios8': {
    bundleId: 'com.demo.ios8',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 8',
    publisherName: 'Publisher 18',
    publisherDomain: buildWebsite(18),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-8/id1000000008',
  },
  'com.demo.ios9': {
    bundleId: 'com.demo.ios9',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 9',
    publisherName: 'Publisher 19',
    publisherDomain: buildWebsite(19),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-9/id1000000009',
  },
  'com.demo.ios10': {
    bundleId: 'com.demo.ios10',
    marketplace: MARKETPLACE.appStore,
    name: 'Demo iOS 10',
    publisherName: 'Publisher 20',
    publisherDomain: buildWebsite(20),
    marketplaceUrl: 'https://apps.apple.com/us/app/demo-ios-10/id1000000010',
  },
};
